<?php
module_load_include('inc', 'mortar', 'mortar.node-access');
module_load_include('inc', 'mortar', 'mortar.field-access');
module_load_include('inc', 'mortar', 'mortar.send-email');
module_load_include('inc', 'mortar', 'mortar.view-alter');
module_load_include('inc', 'mortar', 'mortar.user-alter');
module_load_include('inc', 'mortar', 'mortar.cd-node-alter');
module_load_include('inc', 'mortar', 'mortar.tr-node-alter');
module_load_include('inc', 'mortar', 'mortar.miscellaneous');
module_load_include('inc', 'mortar', 'mortar.wf-node-alter');

/*
 *Prepare node to be displayed
 * 
 */
function mortar_node_view_alter(&$build) {
    //Checks if node is SOP
     
    if($node_load = menu_get_object()) {
        $node = node_load($node_load -> nid);
    }
    else {
        return;
    }

    //load user details
    global $user;
    $account = user_load($user -> uid);    
    
    if($node->type == 'controlled_document' ) {
        mortar_controlled_document_node_view_alter($build, $account, $node);
    }
}


/*
 *Adds access options to content types. 
 */
function mortar_node_access($node, $op, $account) {

    if(!isset($node -> type)) {
        return NODE_ACCESS_IGNORE;
    }
    
    if($node->type == 'ctu' ) {
        //function in node-access.inc
        return mortar_ctu_access($node, $op, $account);
    }
    
    if($node->type == 'controlled_document' ) {
        //function in node-access.inc
        return mortar_controlled_document_access($node, $op, $account);
    }
    

    if($node->type == 'training_record' ) {
        //function in node-access.inc
        return mortar_training_record_access($node, $op, $account);
    }
    
}


/*
 *
 */
function mortar_node_view($node, $view_mode, $langcode) {
    if($node -> nid == 4175) {
        $node -> content['#fieldgroups']['group_all_sops'] -> label = 'My Controlled Documents';
        $node -> content['#fieldgroups']['group__all_sop_append'] -> label = 'Review Emails';
        $node -> content['#fieldgroups']['group_process_map'] -> weight = '60';
    }
    
    if($node -> type == "cds_display"){
        mortar_cd_process_setup($node, $view_mode, $langcode);
    }
    
    /*
    * Check the user have access permission to OCTO guidelines if not then hide the Horizentale tab from the menu
    */
    global $user;
    $account = user_load($user -> uid);
    $ctu_list = array();
    for($count = 0; $count < count($account -> field_ctu['und']); $count++) {
       $ctu_list[] = $account -> field_ctu['und'][$count][target_id];  
    }
    
    if (in_array('457', $ctu_list, true)) {
       // dpm('found');
    } else {
        $node -> field_view_ht_6 = array();
        $node -> content['field_view_ht_6'] = array();
    }
}


/*
 *
 */
function mortar_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    
    if($form_id == 'views_form_training_record_desktop_display_ol' && isset($form['from'])) {
        //function 
        mortar_training_record_reminder_view_send_email($form, $form_state, $form_id);
    }

    if($form_id == 'views_form_training_record_desktop_display_admin' && isset($form['from'])) {
        //function 
        mortar_training_record_reminder_view_send_email($form, $form_state, $form_id);
    }
    
    if($form_id == 'views_form_all_training_record_related_to_sops_report_page' && isset($form['from'])) {
        //function (for all sop view)
        mortar_training_record_all_sop_view_send_email($form, $form_state, $form_id);
    }
    
    if(($form_id == 'user_profile_form' || $form_id == 'user_register_form') && !in_array('administrator', $user -> roles) && in_array('mortar administrator', $user -> roles)) {
        //function in 
        mortar_user_profile_form_alter($form, $form_state, $form_id, $user);
    }    
    #debug($form_id); user_register_form'
    
}


/*
 * Implements hook_menu_alter().
 */
function mortar_menu_alter(&$items) {
    //custom diff access
    $items['node/%node/revisions']['access arguments'] = array(1);
    $items['node/%node/revisions']['access callback'] = 'mortar_node_revision_access';
   
}


/*
 *
 */
function mortar_css_alter(&$css) {
    #debug($css);
    //add correct css
    
    $css['sites/all/modules/octru/mortar/mortar-main.css'] = array(
                                                                'data' => drupal_get_path('module', 'mortar') . '/mortar-main.css',
                                                                'every_page' => true,
                                                                'media' => 'all',
                                                                'type' => 'file',
                                                                'weight' => 999,
                                                                'preprocess' => true,
                                                                'browsers' => 
                                                                    array (
                                                                        'IE' => true,
                                                                        '!IE' => true,
                                                                    ),
                                                                'group' => 0,
                                                              );
    global $base_url;
    
    if (strpos($base_url,'test') !== false) {
        $css['sites/all/modules/octru/mortar/mortar-test.css'] = array(
                                                                        'data' => drupal_get_path('module', 'mortar') . '/mortar-test.css',
                                                                        'every_page' => true,
                                                                        'media' => 'all',
                                                                        'type' => 'file',
                                                                        'weight' => 999,
                                                                        'preprocess' => true,
                                                                        'browsers' => 
                                                                            array (
                                                                                'IE' => true,
                                                                                '!IE' => true,
                                                                            ),
                                                                        'group' => 0,
                                                                      );
        #drupal_add_css(drupal_get_path('module', 'mortar') . '/mortar-dev.css');
    }
    else if (strpos($base_url,'dev') !== false) {
        $css['sites/all/modules/octru/mortar/mortar-dev.css'] = array(
                                                                        'data' => drupal_get_path('module', 'mortar') . '/mortar-dev.css',
                                                                        'every_page' => true,
                                                                        'media' => 'all',
                                                                        'type' => 'file',
                                                                        'weight' => 999,
                                                                        'preprocess' => true,
                                                                        'browsers' => 
                                                                            array (
                                                                                'IE' => true,
                                                                                '!IE' => true,
                                                                            ),
                                                                        'group' => 0,
                                                                      );
        #drupal_add_css(drupal_get_path('module', 'mortar') . '/mortar-dev.css');
    }
    else {
        #drupal_add_css(drupal_get_path('module', 'mortar') . '/mortar-live.css');
        $css['sites/all/modules/octru/mortar/mortar-live.css'] = array(
                                                                        'data' => drupal_get_path('module', 'mortar') . '/mortar-live.css',
                                                                        'every_page' => true,
                                                                        'media' => 'all',
                                                                        'type' => 'file',
                                                                        'weight' => 999,
                                                                        'preprocess' => true,
                                                                        'browsers' => 
                                                                            array (
                                                                                'IE' => true,
                                                                                '!IE' => true,
                                                                            ),
                                                                        'group' => 0,
                                                                       );
    }
 
}

/**
 * Access callback for the node revisions page.
 */
function mortar_node_revision_access($node, $op = 'view') {
    global $user;
    
    if(in_array('administrator', $user -> roles) || in_array('mortar administrator', $user -> roles)) {
        return TRUE;
    }
    //default diff     
    $may_revision_this_type = variable_get('diff_enable_revisions_page_node_' . $node->type, TRUE) || user_access('administer nodes');
    
    if($node -> type == 'controlled_document') {
        //4 = Active - Undergoing revision, 6 - Draft 
        $cd_status = $node -> field_status['und'][0]['target_id'] == 4 || $node -> field_status['und'][0]['target_id'] == 6;
    }
    else {
        $cd_status = TRUE;
    }
    //author
    $node_uid = $node -> uid == $user -> uid;
    
    return $may_revision_this_type && _node_revision_access($node, $op) && $cd_status && $node_uid;


}


/*
 * Implements hook_presave_alter().
 */
function mortar_node_presave($node){
    if(isset($node->log) && !empty($node->log)){
        $tid = $node->field_review_version_number['und'][0]['tid'];
        $term = taxonomy_term_load($tid);
        $name = $term->name;
        $node->log = 'Review Version Number ('.$name.') - '.$node->log;
    }
}


/*
 * Including Process map using html5 map and for highlighting each image on hover event with maphighlight.js file.
*/
function mortar_cd_process_setup($node, $view_mode, $langcode) {
    $node -> content['field_process_map'][0]['#markup'] = '	
            <img src="/sites/default/files/new_process_map.png" alt="process map" class="map" usemap="#ImageMap" />
            <map name="ImageMap">
            
                <area alt="" title="" href="/controlled-doc/form/004" shape="rect" coords="27,67,161,124" />
                <area alt="" title="" href="/controlled-doc/sop/gen-004" shape="rect" coords="221,59,347,118" />
                
                <area alt="" title="" href="/controlled-doc/sop/gen-005" shape="rect" coords="21,209,115,268" />
                <area alt="" title="" href="/controlled-doc/sop/gen-052" shape="rect" coords="130,211,231,266" />
                <area alt="" title="" href="/controlled-doc/sop/gen-010" shape="poly" coords="258,172,259,231,344,229,343,172" />
                <area alt="" title="" href="/controlled-doc/sop/dm-001" shape="rect" coords="358,177,444,211" />
                <area alt="" title="" href="/controlled-doc/sop/dm-004" shape="rect" coords="458,178,543,227" />
                <area alt="" title="" href="/controlled-doc/sop/dm-008" shape="rect" coords="561,180,643,229" />
                <area alt="" title="" href="/controlled-doc/sop/gen-051" shape="rect" coords="654,172,753,223" />
                <area alt="" title="" href="/controlled-doc/sop/gen-030" shape="rect" coords="22,280,98,336" />
                <area alt="" title="" href="/controlled-doc/sop/gen-018" shape="rect" coords="141,277,216,399" />
                <area alt="" title="" href="/controlled-doc/sop/gen-011" shape="poly" coords="253,236,253,293,341,291,342,235" />
                <area alt="" title="" href="/controlled-doc/sop/dm-002" shape="rect" coords="353,216,428,268" />
                <area alt="" title="" href="/controlled-doc/sop/dm-006" shape="rect" coords="452,235,523,271" />
                <area alt="" title="" href="/controlled-doc/sop/gen-016" shape="rect" coords="564,240,639,295" />
                <area alt="" title="" href="/controlled-doc/sop/gen-034" shape="rect" coords="23,347,118,407" />
                <area alt="" title="" href="/controlled-doc/sop/gen-013" shape="poly" coords="259,300,259,362,333,358,332,298" />
                <area alt="" title="" href="/controlled-doc/sop/dm-003" shape="rect" coords="355,276,425,330" />
                <area alt="" title="" href="/controlled-doc/sop/stats-002" shape="rect" coords="450,279,554,335" />
                <area alt="" title="" href="/controlled-doc/sop/gen-017" shape="rect" coords="564,302,642,358" />
                <area alt="" title="" href="/controlled-doc/sop/dm-005" shape="rect" coords="352,339,455,404" />
                <area alt="" title="" href="/controlled-doc/sop/stats-001" shape="rect" coords="464,343,528,400" />
                <area alt="" title="" href="/controlled-doc/sop/gen-037" shape="rect" coords="562,365,635,406" />
                <area alt="" title="" href="/controlled-doc/sop/gen-019" shape="rect" coords="669,330,759,385" />
                
                
                <area alt="" title="" href="/controlled-doc/sop/gen-027" shape="rect" coords="8,422,94,481" />
                <area alt="" title="" href="/controlled-doc/sop/gen-028" shape="rect" coords="105,422,187,459" />
                <area alt="" title="" href="/controlled-doc/sop/gen-029" shape="rect" coords="204,423,283,463" />
                <area alt="" title="" href="/controlled-doc/sop/gen-011"  shape="poly" coords="302,425,301,479,391,475,389,424" />
                <area alt="" title="" href="/controlled-doc/sop/gen-033" shape="rect" coords="394,420,470,473" />
                <area alt="" title="" href="/controlled-doc/sop/gen-014" shape="rect" coords="478,420,555,477" />
                <area alt="" title="" href="/controlled-doc/sop/stats-004" shape="rect" coords="566,422,656,472" />
                <area alt="" title="" href="/controlled-doc/sop/gen-025" shape="rect" coords="662,424,755,468" />
                <area alt="" title="" href="/controlled-doc/sop/dm-009" shape="rect" coords="8,492,101,536" />
                <area alt="" title="" href="/controlled-doc/sop/gen-032" shape="rect" coords="105,468,201,507" />
                <area alt="" title="" href="/controlled-doc/sop/gen-010" shape="rect" coords="209,470,297,521" />
                
                <area alt="" title="" href="/controlled-doc/sop/gen-036" shape="poly" coords="258,366,258,408,334,407,334,366" />
                
                
                <area alt="" title="" href="/controlled-doc/sop/gen-022" shape="rect" coords="405,488,480,546" />
                <area alt="" title="" href="/controlled-doc/sop/gen-015" shape="rect" coords="498,489,580,541" />
                <area alt="" title="" href="/controlled-doc/sop/dm-010" shape="rect" coords="587,484,667,531" />
                <area alt="" title="" href="/controlled-doc/sop/gen-026" shape="poly" coords="677,482,677,532,762,530,761,482"  />
                <area alt="" title="" href="/controlled-doc/sop/stats-003" shape="rect" coords="9,546,110,602" />
                <area alt="" title="" href="/controlled-doc/sop/gen-023" shape="rect" coords="115,516,205,558" />
                <area alt="" title="" href="/controlled-doc/sop/gen-035" shape="rect" coords="213,531,305,566" />
                <area alt="" title="" href="/controlled-doc/sop/dm-007" shape="poly" coords="312,493,313,549,393,545,393,493" />
                <area alt="" title="" href="/controlled-doc/sop/gen-012" shape="poly" coords="345,558,346,616,430,611,430,559" />
                <area alt="" title="" href="/controlled-doc/sop/gen-043" shape="poly" coords="442,555,444,617,504,615,504,557" />
                <area alt="" title="" href="/controlled-doc/sop/gen-020" shape="poly" coords="519,554,518,616,578,611,577,554" />
                <area alt="" title="" href="/controlled-doc/sop/gen-024" shape="poly" coords="593,541,593,621,668,621,668,541" />
                <area alt="" title="" href="/controlled-doc/sop/gen-040" shape="poly" coords="681,540,681,619,743,616,743,539" />
                <area alt="" title="" href="/controlled-doc/sop/stats-006" shape="rect" coords="118,570,219,614" />
                <area alt="" title="" href="/controlled-doc/sop/gen-042" shape="poly" coords="251,570,251,615,333,615,334,573" />
                
                
                <area alt="" title="" href="/controlled-doc/sop/gen-045" shape="rect" coords="11,631,88,687" />
                <area alt="" title="" href="/controlled-doc/sop/gen-044" shape="rect" coords="92,631,187,685" />
                <area alt="" title="" href="/controlled-doc/sop/dm-011" shape="rect" coords="194,633,277,684" />
                <area alt="" title="" href="/controlled-doc/sop/stats-005" shape="rect" coords="283,633,380,682" />
                <area alt="" title="" href="/controlled-doc/sop/gen-046" shape="rect" coords="382,632,480,683" />
                <area alt="" title="" href="/controlled-doc/sop/gen-048" shape="rect" coords="485,633,573,683" />
                <area alt="" title="" href="/controlled-doc/sop/gen-047" shape="rect" coords="579,632,673,687" />
                <area alt="" title="" href="/controlled-doc/sop/gen-050" shape="rect" coords="679,631,761,686" />
                

                <area alt="" title="001" href="/controlled-doc/sop/gen-001" shape="poly" coords="788,38,787,82,903,78,901,36" />
                <area alt="" title="002" href="/controlled-doc/sop/gen-002" shape="poly" coords="777,90,778,149,847,148,846,90" />
                <area alt="" title="008" href="/controlled-doc/sop/gen-008" shape="poly" coords="854,87,855,147,922,146,923,89" />
                <area alt="" title="003" href="/controlled-doc/sop/gen-003" shape="poly" coords="772,156,773,214,855,211,851,156" />
                <area alt="" title="006" href="/controlled-doc/sop/gen-006" shape="poly" coords="860,161,861,224,917,220,918,157" />
                <area alt="" title="009" href="/controlled-doc/sop/gen-009" shape="poly" coords="778,224,777,288,837,283,839,223" />
                <area alt="" title="055" href="/controlled-doc/sop/gen-055" shape="poly" coords="849,227,847,319,919,314,919,227" />
                <area alt="" title="007" href="/controlled-doc/sop/gen-007" shape="poly" coords="780,330,779,390,892,388,893,329" />
                <area alt="" title="021" href="/controlled-doc/sop/gen-021" shape="poly" coords="779,399,779,481,842,477,842,400" />
                <area alt="" title="031" href="/controlled-doc/sop/gen-031" shape="poly" coords="849,402,848,476,917,473,919,400" />
                <area alt="" title="038" href="/controlled-doc/sop/gen-038" shape="poly" coords="779,487,778,534,898,533,897,487" />
                <area alt="" title="049" href="/controlled-doc/sop/gen-049" shape="poly" coords="777,542,776,595,897,593,899,542" />
                <area alt="" title="Its-001 - Its-009" href="/controlled-doc/sop/its-001" shape="poly" coords="774,605,774,674,910,669,909,603" />
                
            </map>
	
            <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
            <script type="text/javascript" src="/sites/default/files/js/jquery.maphilight.min.js"></script>
            <script type="text/javascript">$(function() {
                $(".map").maphilight({ "strokeWidth": 1, "strokeColor":"42859b", "fill": "B0E57C", "fillColor": "336699", "fillOpacity": 0.7, "singleSelect": true });
            });
            </script>'
        ;
 }

/*
 *<area shape="poly" alt="GEN-004" href="/controlled-doc/sop/gen-004" coords="222, 63, 347, 63, 347, 111, 337, 112, 320, 113, 303, 115, 286, 118, 270, 121, 255, 123, 242, 123, 230, 121, 222, 119" />
                <area shape="poly" alt="OF-004" href="/controlled-doc/form/004" coords="34, 69, 153, 69, 158, 73, 161, 79, 161, 115, 158, 122, 154, 123, 34, 125, 30, 122, 28, 119, 26, 77, 28, 75" />
                
                <area shape="poly" alt="GEN-19" href="/controlled-doc/sop/gen-019" coords="671, 332, 762, 332, 762, 379, 753, 379, 739, 381, 727, 382, 716, 385, 702, 389, 692, 389, 682, 388, 670, 386" />
                <area shape="poly" alt="GEN-37" href="/controlled-doc/sop/gen-037" coords="562, 406, 562, 364, 637, 365, 637, 400, 630, 400, 619, 401, 611, 403, 602, 405, 594, 407, 585, 408, 577, 408" />
                <area shape="poly" alt="GEN-17" href="/controlled-doc/sop/gen-017" coords="563, 304, 641, 303, 641, 351, 631, 351, 614, 354, 600, 358, 590, 361, 578, 361, 570, 360, 562, 359" />
                <area shape="poly" alt="GEN-16" href="/controlled-doc/sop/gen-016" coords="566, 297, 566, 240, 640, 241, 640, 288, 630, 289, 616, 291, 603, 296, 594, 300, 584, 300, 575, 300" />
                <area shape="poly" coords="561, 230, 561, 181, 643, 181, 642, 225, 631, 225, 621, 225, 611, 230, 598, 234, 587, 235, 573, 233" href="/controlled-doc/sop/dm-008" alt="DM-008" />
                <area shape="poly" alt="STATS-001" href="/controlled-doc/sop/stats-001" coords="464, 400, 464, 345, 528, 345, 528, 393, 519, 393, 508, 396, 497, 401, 490, 404, 482, 404, 472, 404" />
                <area shape="poly" alt="STATS-002" href="/controlled-doc/sop/stats-002" coords="450, 334, 450, 278, 557, 278, 557, 327, 548, 327, 536, 328, 527, 329, 516, 331, 508, 334, 500, 335, 488, 338, 481, 338, 470, 337, 463, 336" />
                <area shape="poly" alt="DM-006" href="/controlled-doc/sop/dm-006" coords="454, 271, 454, 237, 525, 237, 525, 268, 518, 268, 508, 269, 496, 271, 486, 273, 478, 275, 470, 275, 462, 274" />
                <area shape="poly" alt="DM-004" href="/controlled-doc/sop/dm-004" coords="457, 230, 457, 180, 544, 181, 544, 223, 536, 223, 525, 223, 512, 225, 502, 229, 494, 231, 486, 232, 476, 233, 468, 232" />
                <area shape="poly" alt="DM-005" href="/controlled-doc/sop/dm-005" coords="352, 341, 455, 341, 455, 397, 449, 397, 436, 399, 424, 400, 412, 404, 400, 408, 392, 409, 380, 411, 374, 411, 366, 409, 359, 409, 352, 407" />
                <area shape="poly" alt="DM-003" href="/controlled-doc/sop/dm-003" coords="354, 331, 354, 277, 426, 277, 425, 325, 414, 325, 403, 327, 392, 331, 380, 335, 369, 335, 362, 334" />
                <area shape="poly" alt="DM-002" href="/controlled-doc/sop/dm-002" coords="354, 269, 354, 217, 430, 217, 430, 261, 420, 261, 410, 262, 402, 263, 394, 266, 389, 270, 376, 270, 368, 271, 360, 271" />
                <area shape="poly" alt="DM-001" href="/controlled-doc/sop/dm-001" coords="358, 211, 358, 177, 445, 176, 445, 206, 436, 206, 426, 207, 416, 208, 407, 209, 397, 211, 389, 213, 378, 213, 370, 211" />
                <area shape="poly" alt="GEN-013" href="/controlled-doc/sop/gen-013" coords="260, 366, 260, 308, 336, 307, 335, 359, 327, 359, 317, 360, 308, 363, 299, 365, 290, 369, 280, 369, 272, 369" />
                <area shape="poly" alt="GEN-011" href="/controlled-doc/sop/gen-011" coords="259, 300, 258, 245, 348, 245, 348, 292, 338, 291, 326, 293, 310, 296, 292, 301, 275, 302" />
                <area shape="poly" alt="GEN-010" href="/controlled-doc/sop/gen-010" coords="261, 232, 261, 178, 349, 178, 348, 224, 336, 225, 324, 226, 314, 229, 302, 232, 288, 235, 275, 235, 266, 233" />
                <area shape="poly" alt="GEN-018" href="/controlled-doc/sop/gen-018" coords="134, 372, 134, 241, 211, 241, 211, 355, 202, 356, 193, 358, 181, 365, 175, 371, 162, 379, 155, 380, 148, 380, 140, 377" />
                <area shape="poly" alt="GEN-034" href="/controlled-doc/sop/gen-034" coords="22, 347, 120, 347, 119, 399, 113, 400, 105, 400, 94, 402, 83, 404, 72, 407, 66, 409, 58, 410, 47, 411, 38, 410, 30, 409, 21, 407" />
                <area shape="poly" alt="GEN-030" href="/controlled-doc/sop/gen-030" coords="22, 282, 98, 281, 98, 330, 91, 331, 80, 331, 71, 334, 53, 340, 47, 340, 38, 340, 30, 339, 21, 338" />
                <area shape="poly" alt="GEN-005" href="/controlled-doc/sop/gen-005" coords="22, 270, 22, 211, 116, 210, 114, 262, 102, 262, 87, 265, 73, 269, 59, 273, 46, 273, 34, 273" />
    
                <area shape="poly" coords="692, 616, 692, 542, 759, 541, 759, 607, 744, 610, 724, 620, 709, 622" href="/controlled-doc/sop/gen-040" alt="GEN-040" />
                <area shape="poly" coords="608, 616, 609, 541, 685, 540, 685, 605, 671, 608, 653, 615, 638, 621, 625, 622" href="/controlled-doc/sop/gen-024" alt="GEN-024" />
                <area shape="poly" coords="540, 608, 541, 554, 601, 552, 600, 602, 589, 602, 572, 608, 556, 612" href="/controlled-doc/sop/gen-020" alt="GEN-020" />
                <area shape="poly" coords="455, 593, 456, 559, 535, 559, 534, 590, 523, 590, 505, 593, 486, 596, 468, 596" href="/controlled-doc/sop/gen-043" alt="GEN-043" />
                <area shape="poly" coords="361, 612, 361, 560, 450, 560, 450, 604, 436, 605, 421, 607, 407, 611, 391, 614, 379, 614" href="/controlled-doc/sop/gen-012" alt="GEN-012" />
                <area shape="poly" coords="272, 598, 272, 548, 355, 548, 355, 591, 345, 593, 332, 593, 318, 598, 302, 602, 291, 602" href="/controlled-doc/sop/dm-007" alt="DM-007" />
                <area shape="poly" coords="217, 613, 217, 542, 270, 541, 270, 602, 252, 607, 243, 613, 234, 617, 226, 616" href="/controlled-doc/sop/gen-035" alt="GEN-035" />
                <area shape="poly" coords="125, 615, 125, 574, 208, 574, 207, 609, 196, 609, 183, 611, 169, 613, 157, 616, 141, 618" href="/controlled-doc/sop/gen-042" alt="GEN-042" />
                <area shape="poly" coords="130, 567, 130, 526, 212, 526, 211, 561, 202, 562, 185, 564, 170, 567, 158, 569, 144, 569" href="/controlled-doc/sop/gen-023" alt="GEN-023" />
                <area shape="poly" coords="14, 606, 15, 548, 112, 549, 111, 599, 100, 598, 85, 600, 68, 604, 48, 608, 35, 609" href="/controlled-doc/sop/stats-003" alt="STATS-003" />
                <area shape="poly" coords="673, 531, 673, 488, 757, 488, 757, 526, 742, 526, 726, 529, 710, 532, 696, 534, 682, 534" href="/controlled-doc/sop/gen-026" alt="GEN-026" />
                <area shape="poly" coords="587, 532, 587, 486, 669, 486, 669, 527, 659, 527, 645, 529, 626, 535, 612, 536, 596, 535" href="/controlled-doc/sop/dm-010" alt="DM-010" />
                <area shape="poly" coords="498, 544, 498, 489, 582, 489, 582, 537, 572, 537, 557, 539, 545, 543, 531, 548, 519, 549" href="/controlled-doc/sop/gen-015" alt="GEN-015" />
                <area shape="poly" coords="415, 555, 415, 495, 493, 494, 493, 545, 482, 546, 467, 550, 452, 553, 438, 557, 429, 557" href="/controlled-doc/sop/gen-022" alt="GEN-022" />
                <area shape="poly" coords="332, 539, 332, 491, 409, 491, 409, 532, 398, 532, 378, 536, 364, 540, 351, 542" href="/controlled-doc/sop/gen-036" alt="GEN-036" />
                <area shape="poly" coords="238, 535, 237, 482, 326, 482, 325, 527, 307, 529, 291, 533, 276, 536, 259, 538" href="/controlled-doc/sop/gen-010" alt="GEN-010" />
                <area shape="poly" coords="129, 475, 226, 475, 226, 510, 215, 510, 198, 511, 176, 517, 165, 517, 150, 517, 141, 516, 128, 517" href="/controlled-doc/sop/gen-032" alt="GEN-032" />
                <area shape="poly" coords="20, 539, 20, 493, 112, 494, 111, 533, 97, 535, 78, 537, 61, 541, 46, 542" href="/controlled-doc/sop/dm-009" alt="DM-009" />
                <area shape="poly" coords="662, 468, 662, 424, 756, 423, 757, 462, 736, 463, 717, 465, 697, 470, 685, 471, 673, 471" href="/controlled-doc/sop/gen-025" alt="GEN-025" />
                <area shape="poly" coords="564, 475, 564, 421, 656, 422, 656, 468, 640, 470, 625, 472, 594, 480, 583, 480" href="/controlled-doc/sop/stats-004" alt="STATS-004" />
                <area shape="poly" coords="479, 478, 479, 421, 556, 421, 556, 470, 539, 473, 523, 477, 505, 483, 495, 482" href="/controlled-doc/sop/gen-014" alt="GEN-014" />
                <area shape="poly" coords="396, 475, 411, 477, 422, 477, 436, 473, 453, 469, 469, 468, 469, 420, 394, 421" href="/controlled-doc/sop/gen-033" alt="GEN-033" />
                <area shape="poly" coords="298, 475, 298, 424, 388, 423, 387, 468, 375, 468, 361, 471, 346, 475, 331, 478, 322, 478, 313, 477" href="/controlled-doc/sop/gen-011" alt="GEN-011" />
                <area shape="poly" coords="206, 464, 205, 425, 282, 425, 282, 458, 276, 460, 263, 460, 255, 462, 244, 465, 234, 466, 224, 468, 214, 466" href="/controlled-doc/sop/gen-029" alt="GEN-029" />
                <area shape="poly" coords="105, 458, 130, 461, 137, 461, 156, 457, 180, 454, 188, 454, 188, 421, 105, 422" href="/controlled-doc/sop/gen-028" alt="GEN-028" />
                <area shape="poly" coords="9, 483, 29, 486, 38, 486, 67, 477, 85, 474, 96, 474, 97, 420, 8, 421" href="/controlled-doc/sop/gen-027" alt="GEN-027" />
    

                <area shape="poly" alt="GEN-047" href="/controlled-doc/sop/gen-047" coords="657, 634, 768, 633, 768, 679, 758, 680, 749, 680, 737, 682, 723, 685, 713, 687, 705, 689, 690, 691, 680, 691, 670, 690, 663, 688, 657, 687" />
                <area shape="poly" alt="GEN-048" href="/controlled-doc/sop/gen-048" coords="563, 636, 649, 635, 648, 676, 632, 676, 620, 678, 605, 683, 594, 685, 585, 685, 572, 685, 564, 683, 562, 683" />
                <area shape="poly" alt="GEN-046" href="/controlled-doc/sop/gen-046" coords="458, 634, 555, 633, 555, 673, 546, 674, 535, 674, 524, 676, 511, 680, 498, 682, 485, 685, 475, 684, 466, 683, 458, 680" />
                <area shape="poly" alt="STATS-005" href="/controlled-doc/sop/stats-005" coords="349, 632, 447, 632, 447, 681, 439, 682, 424, 682, 412, 686, 401, 688, 395, 690, 385, 691, 375, 692, 364, 692, 355, 689, 350, 689" />
                <area shape="poly" alt="DM-011" href="/controlled-doc/sop/dm-011" coords="261, 636, 261, 682, 272, 684, 279, 685, 289, 683, 288, 684, 294, 683, 298, 682, 303, 680, 313, 678, 319, 676, 327, 676, 336, 675, 342, 675, 342, 634" />
                <area shape="poly" alt="GEN-044" href="/controlled-doc/sop/gen-044" coords="125, 634, 246, 634, 246, 675, 228, 675, 213, 676, 200, 678, 183, 681, 169, 683, 154, 684, 141, 683, 130, 682, 124, 682" />
                <area shape="poly" alt="GEN-045" href="/controlled-doc/sop/gen-045" coords="13, 634, 13, 681, 22, 682, 32, 683, 40, 684, 49, 683, 57, 682, 64, 680, 79, 677, 89, 675, 97, 674, 108, 674, 109, 674, 110, 632" />
            
                <area shape="poly" alt="GEN-39" href="/controlled-doc/sop/gen-039" coords="775, 619, 910, 617, 911, 652, 890, 652, 879, 652, 868, 654, 857, 655, 843, 657, 834, 658, 821, 660, 808, 660, 793, 659, 782, 659, 775, 657" />
                <area shape="poly" alt="ITS-003" href="/controlled-doc/sop/its-003" coords="850, 529, 918, 525, 916, 593, 905, 595, 897, 596, 889, 600, 875, 607, 866, 608, 860, 608, 848, 603" />
                <area shape="poly" alt="ITS-002" href="/controlled-doc/sop/its-002" coords="771, 531, 840, 530, 839, 594, 826, 594, 818, 597, 808, 602, 796, 607, 787, 608, 776, 606, 770, 603" />
                <area shape="poly" alt="ITS-001" href="/controlled-doc/sop/its-001" coords="771, 471, 918, 471, 917, 512, 904, 512, 877, 514, 848, 518, 828, 520, 803, 521, 788, 521, 771, 517" />
                <area shape="poly" alt="GEN-038" href="/controlled-doc/sop/gen-038" coords="790, 401, 910, 401, 911, 439, 895, 439, 880, 440, 864, 442, 853, 445, 833, 447, 818, 447, 804, 447, 790, 445" />
                <area shape="poly" alt="GEN-031" href="/controlled-doc/sop/gen-031" coords="845, 313, 915, 312, 915, 374, 904, 375, 891, 379, 880, 384, 868, 388, 860, 389, 853, 387, 844, 385" />
                <area shape="poly" alt="GEN-021" href="/controlled-doc/sop/gen-021" coords="771, 315, 836, 314, 836, 382, 826, 382, 816, 387, 805, 392, 797, 395, 788, 398, 781, 396, 776, 394, 771, 392" />
                <area shape="poly" alt="GEN-007" href="/controlled-doc/sop/gen-007" coords="838, 235, 918, 236, 918, 293, 907, 294, 891, 298, 877, 303, 867, 306, 855, 307, 846, 306, 838, 303" />
                <area shape="poly" alt="GEN-009" href="/controlled-doc/sop/gen-009" coords="772, 242, 773, 299, 785, 302, 794, 302, 808, 297, 820, 291, 833, 291, 833, 240" />
                <area shape="poly" alt="GEN-006" href="/controlled-doc/sop/gen-006" coords="859, 167, 918, 167, 918, 218, 905, 219, 891, 225, 880, 229, 868, 229, 859, 226" />
                <area shape="poly" alt="GEN-003" href="/controlled-doc/sop/gen-003" coords="773, 165, 854, 165, 854, 212, 843, 212, 830, 215, 816, 218, 803, 222, 788, 222, 777, 221, 772, 219" />
                <area shape="poly" alt="GEN-008" href="/controlled-doc/sop/gen-008" coords="852, 96, 920, 95, 920, 145, 911, 145, 905, 146, 898, 148, 889, 152, 878, 156, 868, 157, 863, 156, 857, 155, 851, 153" />
                <area shape="poly" alt="GEN-002" href="/controlled-doc/sop/gen-002" coords="778, 96, 846, 95, 845, 145, 836, 145, 826, 148, 815, 151, 807, 154, 800, 155, 791, 156, 781, 154, 778, 153" />
                <area shape="poly" alt="GEN-001" href="/controlled-doc/sop/gen-001" coords="785, 48, 898, 48, 898, 83, 879, 83, 857, 86, 843, 88, 828, 90, 815, 92, 804, 91, 799, 91, 792, 91, 784, 89" />
           */
